version: "3"
services:
  mysql:
    platform: linux/x86_64
    build: ./mysql/
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d #初期処理のフォルダ。初回起動のみでおｋ
      - ./mysql/db:/var/lib/mysql #ここにデータ永続化するためのファイルが入る。
    ports:
      - 3306:3306
    image: mysqlapp
    container_name: "mysqlapp"
    environment:
      - MYSQL_ROOT_PASSWORD=password
